---
# get openstack facts
- hosts: workstation
  gather_facts: true
  name: gather facts from OpenStack Cloud

  tasks:
    - import_role:
        name: osp-facts
    - include_tasks:
        name: site-3tier-app.yml

...
