---
# get openstack facts
- hosts: workstation
  gather_facts: true
  name: gather facts from OpenStack Cloud
  pre_tasks:
    - import_role:
        name: osp-facts
- name: set base configuration and enable yum repositories
  hosts: all
  gather_facts: false
  become: yes
    - import_role:
        name: 3-tier-setup 

...
