---
# get openstack facts
- hosts: workstation
  gather_facts: true
  tasks:
    - include_role:
        name: osp-facts
      tags: [ osp_workstation, osp_servers ]
    - debug:
        msg: 'OSP Workstation polled successfully'
