# get openstack facts
- name: Call role to gather openstack facts
  include_role: osp_info

#set base configuration and enable yum repositories
- name: Set base configuration and enable yum repositories
  hosts: all
  gather_facts: false
  roles:
    role: base-config
    tags:
      - base-config

# Setup front-end load balancer tier
- name: Setup front-end load balancer tier (haproxy)
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    role: lb-tier
    tags:
        - lbs
        - haproxy

# Setup application servers tier
- name: Setup application servers tier (tomcat)
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - { name: app-tier, tags: [apps, tomcat] }

# Setup database tier
- name: setup database tier (postgresql and httpd)
- hosts: appdbs
  become: yes
  gather_facts: false
  roles:
    - { name: db-tier, tags: [dbs, postgres] }
