# get openstack facts
- hosts: workstation
  gather_facts: true
  roles:
      role: osp-facts

#set base configuration and enable yum repositories

- hosts: all
  gather_facts: true
  roles:
    role: base-config
    tags:
      - base-config

# Setup front-end load balancer tier
- hosts: frontends
  become: yes
  gather_facts: false
  roles:
    role: lb-tier
    tags:
        - lbs
        - haproxy

# Setup application servers tier
- hosts: apps
  become: yes
  gather_facts: false
  roles:
    - { name: app-tier, tags: [apps, tomcat] }

# Setup database tier
- hosts: appdbs
  become: yes
  gather_facts: false
  roles:
    - { name: db-tier, tags: [dbs, postgres] }
