# get openstack facts
- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

#set base configuration and enable yum repositories

-name: set up base configuration on all hosts
  hosts: all
  gather_facts: true
  roles:
    - "{name: base-config, tags: base-config}"

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - "{name: lb-tier, tags: [lbs, haproxy]}"

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - "{name: app-tier, tags: [apps, tomcat]}"

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  gather_facts: false
  roles:
    - "{name: db-tier, tags: [dbs, postgres]}"
