
---
- hosts: workstation
  gather_facts: false
  tasks:
    - blockinfile:
        block: |
            [isolated_group_osp]
            workstation-2d6e.rhpds.opentlc.com ansible_user='cloud-user' ansible_ssh_private_key_file='~/.ssh/open-private-key' ansible_port=22 ansible_connection=ssh ansible_ssh_common_args='-o StrictHostKeyChecking=no'
            [isolated_group_osp:vars]
            controller=tower
        path: /root/ansible-tower-setup-latest/inventory
    - name: "Append inventory file"
      async: 3600
    - name: "Run Ansible Tower setup"
      poll: 36
      shell: /root/ansible-tower-setup-latest/setup.sh
