---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Append inventory file"
    - blockinfile:
        path: /root/ansible-tower-setup-latest/inventory
        block: |
            [isolated_group_osp]
            workstation-2d6e.rhpds.opentlc.com ansible_user='cloud-user' ansible_ssh_private_key_file='~/.ssh/open-private-key' ansible_port=22 ansible_connection=ssh ansible_ssh_common_args='-o StrictHostKeyChecking=no'
            [isolated_group_osp:vars]
            controller=tower
    - shell: /root/ansible-tower-setup-latest/setup.sh
      name: "Run Ansible Tower setup"
      #  async: 3600
      #  poll: 36
