---
  #general purpose variables for system
- name: general purpose Variables
  cloud_vars:
    name: ospcloud

# Variables for acquiring and building out the OS image
image_loc:
   url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
   dest: /tmp/rhel.qcow2

#assigning properties to os image
os_properites:
   cloud: ospcloud
   name: rhel-guest
   container_format: bare
   disk_format: qcow2
   state: present
   filename: /tmp/rhel.qcow2

# variables for creating openstack os_nova_flavor.  Defined as variables in order to provide more flexdibility
flavor_fields:
   M2_Small:
     cloud_name: ospcloud
     flavor_state: present
     flavor_name: m2.small
     flavor_ram: 2048
     flavor_vcpus: 1
     flavor_disk: 10
