---
- name: set base configuration and enable repositories
  include_role:
    name: base-config
    apply:
      tags:
        - base-config
  tags: always

- name: Setup front-end load balancer tier (haproxy)
  include_role:
    name: lb-tier
    apply:
      tags:
        - lbs
        - haproxy
  tags: frontend
