---
- name: install Packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: configure haproxy
  template:
    src:  haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Enable HAProxy
  haproxy:
    state: enabled
    host: '{{ inventory_hostname }}'
    wait: yes
    wait_retries: 10
    wait_interval: 5
...
