---
- name: install Packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: configure haproxy
  template:
    src:  /root/ansible_advance_homework/ansible_advance_homework\roles\lb-tier\templates\haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: start haproxy
...
