---
- name: install Packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: configure haproxy
  template:
    src:  haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: enable HAProxy service via service module
  service:
    name: haproxy
    state: started
