---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
# loop on the values in osp_servers to populate all of the os_server information
- tasks:
  os_server:
    state: "{{ item.value.state }}"
    name: "{{ item..value.name }}"
    cloud: "{{ item.value.cloud }}"
    region_name: "{{ item.value.region_name }}"
    interface: internal
    network: int_subnet
    image: "{{ item.value.image }}"
    flavor: "{{ item.value.flavor }}"
    meta: "{ group: { item.value.meta.group }, deployment_name: { item.value.meta.deployment_name } }"
    security_groups: "{{ item.value.security_group }}"
  with_dict: "{{ osp_servers }}"
  loop_control:
    label: "{{ item.key }}"


- #name: Add floating IP to Servers


- #name: Wait for server to be available
