---
  - name: loop over server deploys
    hosts: localhost
    tasks:
      - include_vars:
          dir: /root/ansible_advance_homework/roles/all/vars
          #file: osp_server_values.yaml
      - debug:
          msg: included vars
      - include_task:
          name: deploy_os_servers.yaml
        with_dict: "{{ osp_servers }}"
      - debug:
          msg: successfully deployed { item.value.name }
...
