---
# main playbook for running tasks to generate instances and apply ext_network

  - name: Running tasks to build frontend osp_servers (haproxy)
    include_tasks: deploy_servers.yaml
      vars_from: frontend_vars.yaml
    tags: frontend_tag

  - name: Running tasks to build app1 server (tomcat)
    include_tasks: deploy_servers.yaml
      vars_from: app1_vars.yaml
    tags: app_tags

  - name: Running tasks to build app2 server (tomcat)
    include_tasks: deploy_servers.yaml
      vars_from: app2_vars.yaml
    tags: app_tags

  - name: Running tasks to build db server (postgresql and httpd)
    include_tasks: deploy_servers.yaml
      vars_from: db_vars.yaml
    tags: db_tags


...
