---
  - name: loop over server deploys
    hosts: localhost    
    tasks:
      - include_vars:
        roles\deploy_os_servers\vars\osp_server_values.yaml
      - include_role:
          name: deploy_os_servers.yaml
        with_dict: "{{ osp_servers }}"
      - debug:
          msg: successfully deployed { item.value.name }
...
