---
  #- name: loop over server deploys
    #hosts: workstation
    #tasks:
#- name: using with_items for OSPCloud instance definitions
#  include_vars:
#    dir: /root/ansible_advance_homework/roles/osp-servers/vars

  ---
    - name: loop over server deploys
      include_tasks: deploy_os_servers.yaml
      with_items: "{{ osp_servers }}"
    - debug:
            msg: successfully deployed { item.value.name }
  ...
