---
# Variables for acquiring and building out the OS image
image_loc:
   url:
   dest:

#assigning properties to os image
os_properites:
   cloud: ospcloud
   name: rhel-guest
   container_format: bare
   disk_format: qcow2
   state: present
   filename: /tmp/rhel.qcow2
