---
# copy the yum repositories to all hosts and chmod to rw for user and read for group and others
- name: Enable yum repository
  copy:
    src:  /root/ansible_advance_homework/roles/base-config/files/all_yum_repositories.repo
    dest: "{{ yum_repo_folder }}/{{ yum_repo_filename }}"
    mode: '0644'
